import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import { Col, Row } from "antd";

const urbanist = Urbanist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.className}`}>
        <Header />
        <main>
          <Row>
            <Col xs={24} md={6}>
              <Navbar />
            </Col>
            <Col xs={24} md={18}>{children}</Col>
          </Row>
        </main>
      </body>
    </html>
  );
}
